image: Visual Studio 2013
shallow_clone: true
clone_depth: 2
<<<<<<< HEAD

install:
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%

build_script: bin\ci-windows.bat

=======
build_script: bin\ci-windows.bat
>>>>>>> postmorph
test: off
branches:
  only:
    - postmorph
